stages:          
  - build

variables:
  IMAGE_NAME: registry.gitlab.com/learning3792551/first_pet

build-job:      
  stage: build
  image: docker:cli
  services:
  - docker:dind

  before_script:
    - echo "$GITLAB_PASSWORD" | docker login -u fnaferm --password-stdin registry.gitlab.com
  script:
    - echo "1/3 Building microservices date-server"
    - docker build -t $IMAGE_NAME:date-server ./src/date-server/
    - echo "Pushing..."
    - docker push $IMAGE_NAME:date-server

    

