stages:          
  - build

variables:
  PROJECT: first_pet
  REGISTRY: registry.gitlab.com/learning3792551


build-job:      
  stage: build
  image: docker:cli
  services:
  - docker:dind

  before_script:
    - echo "$CI_JOB_TOKEN" | docker login -u fnaferm --password-stdin registry.gitlab.com
  script:
    - echo "1/3 Building microservices date-server"
    - docker build -t $REGISTRY/$PROJECT/date-server:dev ./src/date-server/
    - echo "Pushing..."
    - docker push $REGISTRY/$PROJECT/date-server:dev

    

