stages:          
  - build

build-job:      
  stage: build
  image: docker:cli
  services:
  - docker:dind

  script:
    - echo "Building microserver 1/3 date-server"
    - docker build ./src/date-server/
    

